site_name: Sebrae Docs
site_description: "Documentação oficial dos projetos do Sebrae"
site_author: "Rodrigo Lacan"

nav:
  - Home: index.md
  - Devops:
      - Jenkins:
          - Informações do Sistema: devops/jenkins/1_informacao-sistema.md
          - Configuração do Ambiente: devops/jenkins/2_configuracao-ambiente.md
          - Soluções de Problemas Comuns: devops/jenkins/3_solucoes-problemas.md
          - Notas e Observações: devops/jenkins/4_notas.md

theme:
  name: material
  icon: "fa"

  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

plugins:
  - search
  - git-revision-date:

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.arithmatex
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.details
  - codehilite
  - pymdownx.superfences

copyright: Copyright &copy; 2024 Sebrae RR
repo_url: https://github.com/rodrigolacan

extra:
  search:
    language: "pt"
